change = float(input())
number_coins = 0

while change >= 2:
    coin = 2
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 1:
    coin = 1
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.5:
    coin = 0.5
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.2:
    coin = 0.2
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.1:
    coin = 0.1
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.05:
    coin = 0.05
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.02:
    coin = 0.02
    change -= coin
    number_coins += 1
    change = round(change, 2)
while change >= 0.01:
    coin = 0.01
    change -= coin
    number_coins += 1
    change = round(change, 2)
print(number_coins)
